export const characters =
    "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789!@#$%^&*-=_+";

export const words = [
    "lorem",
    "ipsum",
    "dolor",
    "sit",
    "amet",
    "consectetur",
    "adipisicing",
    "elit",
    "quas",
    "vitae",
    "odit",
    "beatae",
    "dolorum",
    "iste",
    "ex",
    "molestiae",
    "adipisci",
    "sequi",
    "quasi",
    "ullam",
    "ipsa",
    "omnis",
    "minus",
    "cupiditate",
    "doloribus",
    "molestias",
    "assumenda",
    "voluptatem",
    "minima",
    "voluptates",
    "corporis",
    "iure",
    "rem",
    "quis",
    "vel",
    "maiores",
    "cum",
    "consequuntur",
    "commodi",
    "voluptate",
    "inventore",
    "deleniti",
    "dolorem",
    "quis",
    "tempora",
    "ab",
    "debitis",
    "velit",
    "ullam",
    "fuga",
];

export const firstNames = [
    "James",
    "Robert",
    "John",
    "Michael",
    "William",
    "David",
    "Richard",
    "Joseph",
    "Thomas",
    "Charles",
    "Christopher",
    "Daniel",
    "Matthew",
    "Anthony",
    "Mark",
    "Donald",
    "Steven",
    "Paul",
    "Andrew",
    "Joshua",
    "Kenneth",
    "Kevin",
    "Brian",
    "George",
    "Edward",
    "Mary",
    "Patricia",
    "Jennifer",
    "Linda",
    "Elizabeth",
    "Barbara",
    "Susan",
    "Jessica",
    "Sarah",
    "Karen",
    "Nancy",
    "Lisa",
    "Betty",
    "Margaret",
    "Sandra",
    "Ashley",
    "Kimberly",
    "Emily",
    "Donna",
    "Michelle",
    "Dorothy",
    "Carol",
    "Amanda",
    "Melissa",
    "Deborah",
];

export const lastNames = [
    "Smith",
    "Johnson",
    "Williams",
    "Brown",
    "Jones",
    "Garcia",
    "Miller",
    "Davis",
    "Rodriguez",
    "Martinez",
    "Hernandez",
    "Lopez",
    "Gonzales",
    "Wilson",
    "Anderson",
    "Thomas",
    "Taylor",
    "Moore",
    "Jackson",
    "Martin",
    "Lee",
    "Perez",
    "Thompson",
    "White",
    "Harris",
    "Sanchez",
    "Clark",
    "Ramirez",
    "Lewis",
    "Robinson",
    "Walker",
    "Young",
    "Allen",
    "King",
    "Wright",
    "Scott",
    "Torres",
    "Nguyen",
    "Hill",
    "Flores",
    "Green",
    "Adams",
    "Nelson",
    "Baker",
    "Hall",
    "Rivera",
    "Campbell",
    "Mitchell",
    "Carter",
    "Roberts",
];

export const countries = [
    "China",
    "India",
    "United States",
    "Indonesia",
    "Pakistan",
    "Brazil",
    "Nigeria",
    "Bangladesh",
    "Russia",
    "Mexico",
    "Japan",
    "Ethiopia",
    "Philippines",
    "Egypt",
    "Vietnam",
    "DR Congo",
    "Iran",
    "Turkey",
    "Germany",
    "France",
    "United Kingdom",
    "Thailand",
    "South Africa",
    "Tanzania",
    "Italy",
    "Myanmar",
    "South Korea",
    "Colombia",
    "Kenya",
    "Spain",
    "Argentina",
    "Algeria",
    "Sudan",
    "Uganda",
    "Iraq",
    "Ukraine",
    "Canada",
    "Poland",
    "Morocco",
    "Uzbekistan",
    "Saudi Arabia",
    "Peru",
    "Afghanistan",
    "Malaysia",
    "Angola",
    "Mozambique",
    "Ghana",
    "Yemen",
    "Nepal",
    "Venezuela",
    "Ivory Coast",
    "Madagascar",
    "Australia",
    "North Korea",
    "Cameroon",
    "Niger",
    "Taiwan",
    "Sri Lanka",
    "Burkina Faso",
    "Mali",
    "Chile",
    "Kazakhstan",
    "Romania",
    "Malawi",
    "Zambia",
    "Syria",
    "Ecuador",
    "Netherlands",
    "Senegal",
    "Guatemala",
    "Chad",
    "Somalia",
    "Zimbabwe",
    "Cambodia",
    "South Sudan",
    "Rwanda",
    "Guinea",
    "Burundi",
    "Benin",
    "Bolivia",
    "Tunisia",
    "Haiti",
    "Belgium",
    "Jordan",
    "Cuba",
    "Greece",
    "Dominican Republic",
    "Czech Republic",
    "Sweden",
    "Portugal",
    "Azerbaijan",
    "Hungary",
    "Honduras",
    "Tajikistan",
    "Israel",
    "Belarus",
    "United Arab Emirates",
    "Papua New Guinea",
    "Austria",
    "Switzerland",
    "Sierra Leone",
    "Togo",
    "Hong Kong (China)",
    "Paraguay",
    "Laos",
    "Libya",
    "Serbia",
    "El Salvador",
    "Lebanon",
    "Kyrgyzstan",
    "Nicaragua",
    "Bulgaria",
    "Turkmenistan",
    "Denmark",
    "Congo",
    "Central African Republic",
    "Finland",
    "Singapore",
    "Slovakia",
    "Norway",
    "Palestine",
    "Costa Rica",
    "New Zealand",
    "Ireland",
    "Kuwait",
    "Liberia",
    "Oman",
    "Panama",
    "Mauritania",
    "Croatia",
    "Georgia",
    "Eritrea",
    "Uruguay",
    "Mongolia",
    "Bosnia and Herzegovina",
    "Puerto Rico (United States)",
    "Armenia",
    "Albania",
    "Qatar",
    "Lithuania",
    "Jamaica",
    "Moldova",
    "Namibia",
    "Gambia",
    "Botswana",
    "Gabon",
    "Lesotho",
    "Slovenia",
    "Latvia",
    "North Macedonia",
    "Kosovo",
    "Guinea-Bissau",
    "Equatorial Guinea",
    "Bahrain",
    "Trinidad and Tobago",
    "Estonia",
    "East Timor",
    "Mauritius",
    "Eswatini",
    "Djibouti",
    "Fiji",
    "Cyprus",
    "Comoros",
    "Bhutan",
    "Guyana",
    "Solomon Islands",
    "Macau (China)",
    "Luxembourg",
    "Montenegro",
    "Western Sahara",
    "Suriname",
    "Cape Verde",
    "Malta",
    "Belize",
    "Brunei",
    "Bahamas",
    "Maldives",
    "Northern Cyprus",
    "Iceland",
    "Transnistria",
    "Vanuatu",
    "Barbados",
    "French Polynesia (France)",
    "New Caledonia (France)",
    "Abkhazia",
    "São Tomé and Príncipe",
    "Samoa",
    "Saint Lucia",
    "Guam (United States)",
    "Curaçao (Netherlands)",
    "Republic of Artsakh",
    "Kiribati",
    "Grenada",
    "Aruba (Netherlands)",
    "Saint Vincent and the Grenadines",
    "Jersey (British Crown Dependency)",
    "Micronesia",
    "Tonga",
    "Antigua and Barbuda",
    "Seychelles",
    "U.S. Virgin Islands (United States)",
    "Isle of Man (British Crown Dependency)",
    "Andorra",
    "Dominica",
    "Cayman Islands (United Kingdom)",
    "Bermuda (United Kingdom)",
    "Guernsey (British Crown Dependency)",
    "Greenland (Denmark)",
    "Marshall Islands",
    "Saint Kitts and Nevis",
    "Faroe Islands (Denmark)",
    "South Ossetia",
    "American Samoa (United States)",
    "Northern Mariana Islands (United States)",
    "Turks and Caicos Islands (United Kingdom)",
    "Sint Maarten (Netherlands)",
    "Liechtenstein",
    "Monaco",
    "Gibraltar (United Kingdom)",
    "San Marino",
    "Saint Martin (France)",
    "Åland (Finland)",
    "British Virgin Islands (United Kingdom)",
    "Palau",
    "Cook Islands (New Zealand)",
    "Anguilla (United Kingdom)",
    "Nauru",
    "Wallis and Futuna (France)",
    "Tuvalu",
    "Saint Barthélemy (France)",
    "Saint Helena, Ascension and Tristan da Cunha (United Kingdom)",
    "Saint Pierre and Miquelon (France)",
    "Montserrat (United Kingdom)",
    "Falkland Islands (United Kingdom)",
    "Christmas Island (Australia)",
    "Norfolk Island (Australia)",
    "Niue (New Zealand)",
    "Tokelau (New Zealand)",
    "Vatican City",
    "Cocos (Keeling) Islands (Australia)",
    "Pitcairn Islands (United Kingdom)",
];

export const cities = [
    "Tokyo",
    "Delhi",
    "Shanghai",
    "São Paulo",
    "Mexico City",
    "Cairo",
    "Mumbai",
    "Beijing",
    "Dhaka",
    "Osaka",
    "New York",
    "Karachi",
    "Buenos Aires",
    "Chongqing",
    "Istanbul",
    "Kolkata",
    "Manila",
    "Lagos",
    "Rio de Janeiro",
    "Tianjin",
    "Kinshasa",
    "Guangzhou",
    "Los Angeles",
    "Moscow",
    "Shenzhen",
    "Lahore",
    "Bangalore",
    "Paris",
    "Bogotá",
    "Jakarta",
    "Chennai",
    "Lima",
    "Bangkok",
    "Seoul",
    "Nagoya",
    "Hyderabad",
    "London",
    "Tehran",
    "Chicago",
    "Chengdu",
    "Nanjing",
    "Wuhan",
    "Ho Chi Minh City",
    "Luanda",
    "Ahmedabad",
    "Kuala Lumpur",
    "Xi'an",
    "Hong Kong",
    "Dongguan",
    "Hangzhou",
    "Foshan",
    "Shenyang",
    "Riyadh",
    "Baghdad",
    "Santiago",
    "Surat",
    "Madrid",
    "Suzhou",
    "Pune",
    "Harbin",
    "Houston",
    "Dallas",
    "Toronto",
    "Dar es Salaam",
    "Miami",
    "Belo Horizonte",
    "Singapore",
    "Philadelphia",
    "Atlanta",
    "Fukuoka",
    "Khartoum",
    "Barcelona",
    "Johannesburg",
    "Saint Petersburg",
    "Qingdao",
    "Dalian",
    "Washington metropolitan area",
    "Yangon",
    "Alexandria",
    "Jinan",
    "Guadalajara",
];

export const streets = [
    "Henley Heath",
    "Sandmere Close",
    "Wickham Orchards",
    "Monarch Parade",
    "Leslie Moor",
    "Charlotte Quadrant",
    "Faringdon",
    "Winton Parkway",
    "Burgess Paddocks",
    "Browning Lea",
    "Denham Gardens",
    "Harris East",
    "Cameron Coppice",
    "Cotswold Leaze",
    "Morgan Place",
    "Wickham Wharf",
    "St Phillip's Close",
    "Lighthouse Score",
    "Beechcroft Loan",
    "Dobsons Close",
    "Wilthorpe Road",
    "Rowan Leys",
    "Pingle Drive",
    "Bruce Field",
    "Cobden Head",
    "Clydesdale Copse",
    "Harris Covert",
    "Gracechurch Street",
    "Conifer Trees",
    "Henley Side",
    "Sparta Close",
    "Brownlow Street",
    "Burgess Nook",
    "Macbeth Place",
    "Ennerdale Broadway",
    "Nelson Newydd",
    "Sackvylle Street",
    "Second Glen",
    "Richards Mill",
    "Don Vale",
    "Cruxwell Street",
    "Lydiate Avenue",
    "Water Gardens",
    "Bessalone Drive",
    "Birchwood Coppice",
    "Botany Bay Close",
    "Hilltop Green",
    "Ash Tree Place",
    "Newlands Vale",
    "Procession Lane",
];

export const genders = ["Male", "Female", "Non binary"];
